spring.application.name=Opportunity
spring.messages.encoding=UTF-8


# Database connection
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.nvnfneolffuylurbwrfg&password=Lilrulas05@!
spring.datasource.username=postgres.nvnfneolffuylurbwrfg
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
