spring.application.name=Opportunity
spring.application.version=1.0.0
spring.messages.encoding=UTF-8

#Running configurations
logging.level.aubaro=INFO
logging.pattern.console=%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
spring.jpa.open-in-view=false

# Database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Banner
spring.banner.location=classpath:banner.txt
spring.banner.charset=UTF-8
spring.main.banner-mode=console
spring.output.ansi.enabled=ALWAYS
