spring.application.name=Opportunity
spring.application.version=1.0.0
spring.application.ambient=dev
spring.messages.encoding=UTF-8

#Running configurations
logging.level.aubaro=INFO
logging.pattern.console=%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
spring.jpa.open-in-view=false

# Database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=180000
spring.datasource.hikari.keepalive-time=120000

# Banner
spring.banner.location=classpath:banner.txt
spring.banner.charset=UTF-8
spring.main.banner-mode=console
spring.output.ansi.enabled=ALWAYS

# tokens configuration
jwt.secret=${JWT_SECRET}
jwt.access-expiration-ms=${JWT_ACCESS_EXPIRATION_MS}
jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS}
server.port=${PORT}
